### ISSUE TITLE
Ajustes #1

### ISSUE THREAD

**Issue by PauloWaib** [dmarcogabriel/react-terrafinder-web#1]
### Cabeçalho:
- [x] Remover sublinhado dos links
- [x] Deixar "Fale conosco!"

### Busca Home:
- [x] Tipo de propriedade só mostra as opções que estão cadastradas?
- [x] Deixar intervalo de área entre 1 ah até 350 ah
- [x] Deixar intervalo de preço entre R$5.000 até R$50.000.000

### O que você precisa?
- [x] Arrumar altura dos botões Comprar / Virar Pro
- [x] Link do Virar Pro mandar para a página de Fale Conosco

### Planos:
- [x] Trocar valor de R$50,00 pra R$129,00 no plano intermediário
- [x] Card, título e letra do botão Verde trocar pra #32cd8b (mais visível)
- [x] Card, título e letra do botão Amarelo trocar pra #cd8632 (mais vísivel)
- [x] Card, título e letra do botão Azul trocar pra #3279cd (mais vísivel)

### Página de busca
- [x] Implementar busca vazia (Não encontramos nenhum resultado para a sua pesquisa, utilize os filtros acima para procurar outros)
- [x] Os filtros tão bem diferentes do que tá lá no Adobe, se der pra aproximar
- [x] Faltam os filtros de cidade, e busca por código do anúncio
- [ ] Faltou os filtros avançados (mas acho que não precisa implementar n se for dar mt trabalho)

### Tela de login
- [x] Login não está funcionando (usuário testado: teste@email.com senha aaaaaa)
- [x] Trocar imagem de background

![Farm_vast_landscape-Landscape_HD_Wallpaper_1366x768](https://user-images.githubusercontent.com/54338946/141040978-42b77b98-3f1c-4d08-8149-fe12573b455f.jpg)

- [x] Adicionar abaixo do botão "Fazer login" um "Voltar" que leva de volta pra Home
- [x] Diminuir o comprimento dos campos de login e centralizar eles

### Recuperação de senha
- [x] Não está enviando e-mail 
- [x] Não consegui testar se redefine a senha mesmo

### Criação de anúncio
- [x] Não consegui testar porque o login não funfou

### Listagem de anúncio
- [x] Não consegui testar porque a busca não retornou nada

### Detalhes do anúncio
- [x] Não consegui testar porque não encontrei anúncios cadastrados/não deu pra criar

### Quem somos
- [x] Aumentar padding lateral do texto

### Fale Conosco
- [x] O item Fale Conosco no rodapé não está com link

### Planos
- [x] Fazer trocas igual à seção de planos da home

**Comment by dmarcogabriel** [comment]
Ajustes concluídos, apenas os filtros avançados ficaram para depois.
